interface DenonymCodesType {[key: string]: string};

export const DenonymCodes: DenonymCodesType = {
    "Abkhaz": "Abkhazia",
    "Abkhazian": "Abkhazia",
    "Abkhazians": "Abkhazia",
    "Afghan": "Afghanistan",
    "Afghans": "Afghanistan",
    "Åland Island": "Åland",
    "Ålanders": "Åland",
    "Albanian": "Albania",
    "Albanians": "Albania",
    "Algerian": "Algeria",
    "Algerians": "Algeria",
    "American Samoan": "American Samoa",
    "American Samoans": "American Samoa",
    "Andorran": "Andorra",
    "Andorrans": "Andorra",
    "Angolan": "Angola",
    "Angolans": "Angola",
    "Anguillan": "Anguilla",
    "Anguillans": "Anguilla",
    "Antarctic": "Antarctica",
    "Antarcticans": "Antarctica",
    "Antiguan": "Antigua and Barbuda",
    "Barbudan": "Antigua and Barbuda",
    "Antiguans": "Antigua and Barbuda",
    "Barbudans": "Antigua and Barbuda",
    "Argentine": "Argentina",
    "Argentinian": "Argentina",
    "Argentines": "Argentina",
    "Argentinians": "Argentina",
    "Armenian": "Armenia",
    "Armenians": "Armenia",
    "Aruban": "Aruba",
    "Arubans": "Aruba",
    "Australian": "Australia",
    "Australians": "Australia",
    "Austrian": "Austria",
    "Austrians": "Austria",
    "Azerbaijani": "Azerbaijan",
    "Azeri": "Azerbaijan",
    "Azerbaijanis": "Azerbaijan",
    "Azeris": "Azerbaijan",
    "Bahamian": "The Bahamas",
    "Bahamians": "The Bahamas",
    "Bahraini": "Bahrain",
    "Bahrainis": "Bahrain",
    "Bangladeshi": "Bangladesh",
    "Bangladeshis": "Bangladesh",
    "Barbadian": "Barbados",
    "Barbadians": "Barbados",
    "Belarusian": "Belarus",
    "Belarusians": "Belarus",
    "Belgian": "Belgium",
    "Belgians": "Belgium",
    "Belizean": "Belize",
    "Belizeans": "Belize",
    "Beninese": "Benin",
    "Beninois": "Benin",
    "Bermudian": "Bermuda",
    "Bermudan": "Bermuda",
    "Bermudians": "Bermuda",
    "Bermudans": "Bermuda",
    "Bhutanese": "Bhutan",
    "Bolivian": "Bolivia",
    "Bolivians": "Bolivia",
    "Bonaire": "Bonaire",
    "Bonairean": "Bonaire",
    "Bonaire Dutch": "Bonaire",
    "Bosnian": "Bosnia and Herzegovina",
    "Herzegovinian": "Bosnia and Herzegovina",
    "Bosnians": "Bosnia and Herzegovina",
    "Herzegovinians": "Bosnia and Herzegovina",
    "Botswanian": "Botswana",
    "Batswana (singular Motswana)": "Botswana",
    " Botswanians": "Botswana",
    "Bouvet Island": "Bouvet Island",
    "Bouvet Islanders": "Bouvet Island",
    "Brazilian": "Brazil",
    "Brazilians": "Brazil",
    "BIOT": "British Indian Ocean Territory",
    "British": "United Kingdom",
    "Bruneian": "Brunei",
    "Bruneians": "Brunei",
    "Bulgarian": "Bulgaria",
    "Bulgarians": "Bulgaria",
    "Burkinabé": "Burkina Faso",
    "Burkinabè": "Burkina Faso",
    "Burmese": "Myanmar",
    "Burman": "Burma",
    "Burundian": "Burundi",
    "Burundians": "Burundi",
    "Barundi": "Burundi",
    "Cabo Verdean": "Cabo Verde",
    "Cabo Verdeans": "Cabo Verde",
    "Cambodian": "Cambodia",
    "Cambodians": "Cambodia",
    "Cameroonian": "Cameroon",
    "Cameroonians": "Cameroon",
    "Canadian": "Canada",
    "Canadians": "Canada",
    "Caymanian": "Cayman Islands",
    "Caymanians": "Cayman Islands",
    "Central African": "Central African Republic",
    "Central Africans": "Central African Republic",
    "Chadian": "Chad",
    "Chadians": "Chad",
    "Chilean": "Chile",
    "Chileans": "Chile",
    "Chinese": "China",
    "Christmas Island": "Christmas Island",
    "Christmas Islanders": "Christmas Island",
    "Cocos Island": "Cocos (Keeling) Islands",
    "Cocos Islanders": "Cocos (Keeling) Islands",
    "Colombian": "Colombia",
    "Colombians": "Colombia",
    "Comoran": "Comoros",
    "Comorian": "Comoros",
    "Comorans": "Comoros",
    "Comorians": "Comoros",
    "Congolese": "Republic of the Congo",
    "Cook": "Cook Islands",
    "Cook Islanders": "Cook Islands",
    "Costa Rican": "Costa Rica",
    "Costa Ricans": "Costa Rica",
    "Croatian": "Croatia",
    "Croatians": "Croatia",
    "Croats": "Croatia",
    "Cuban": "Cuba",
    "Cubans": "Cuba",
    "Curaçaoan": "Curaçao",
    "Curaçaoans": "Curaçao",
    "Cypriot": "Cyprus",
    "Cypriots": "Cyprus",
    "Czech": "Czech Republic",
    "Czechs": "Czech Republic",
    "Danish": "Denmark",
    "Danes": "Denmark",
    "Djiboutian": "Djibouti",
    "Djiboutians": "Djibouti",
    "Dominican": "Dominican Republic",
    "Dominicans": "Dominican Republic",
    "Timorese": "Timor-Leste",
    "Ecuadorian": "Ecuador",
    "Ecuadorians": "Ecuador",
    "Egyptian": "Egypt",
    "Egyptians": "Egypt",
    "Salvadoran": "El Salvador",
    "Salvadorans": "El Salvador",
    "Salvadorians": "El Salvador",
    "Salvadoreans": "El Salvador",
    "English": "England",
    "Englishmen and Englishwomen": "England",
    "Equatorial Guinean": "Equatorial Guinea",
    "Equatoguinean": "Equatorial Guinea",
    "Equatorial Guineans": "Equatorial Guinea",
    "Equatoguineans": "Equatorial Guinea",
    "Eritrean": "Eritrea",
    "Eritreans": "Eritrea",
    "Estonian": "Estonia",
    "Estonians": "Estonia",
    "Swazi": "Eswatini",
    "Swati": "Eswatini",
    "Swazis": "Eswatini",
    "Ethiopian": "Ethiopia",
    "Ethiopians": "Ethiopia",
    "Habesha": "Ethiopia",
    "European": "European Union",
    "Europeans": "European Union",
    "Falkland Island": "Falkland Islands",
    "Falkland Islanders": "Falkland Islands",
    "Faroese": "Faroe Islands",
    "Fijian": "Fiji",
    "Fijians": "Fiji",
    "Finnish": "Finland",
    "Finns": "Finland",
    "French ST": "French Southern Territories",
    "French": "France",
    "French Guianese": "French Guiana",
    "French Polynesian": "French Polynesia",
    "French Polynesians": "French Polynesia",
    "French Southern Territories": "French Southern Territories",
    "Gabonese": "Gabon",
    "Gabonaise": "Gabon",
    "Gambian": "The Gambia",
    "Gambians": "The Gambia",
    "Georgian": "Georgia",
    "Georgians": "Georgia",
    "German": "Germany",
    "Germans": "Germany",
    "Ghanaian": "Ghana",
    "Ghanaians": "Ghana",
    "Gibraltar": "Gibraltar",
    "Gibraltarians": "Gibraltar",
    "Greek": "Greece",
    "Hellenic": "Greece",
    "Greeks": "Greece",
    "Hellenes": "Greece",
    "Greenland": "Greenland",
    "Greenlanders": "Greenland",
    "Grenadian": "Grenada",
    "Grenadians": "Grenada",
    "Guadeloupe": "Guadeloupe",
    "Guadeloupians": "Guadeloupe",
    "Guadeloupeans": "Guadeloupe",
    "Guamanian": "Guam",
    "Guamanians": "Guam",
    "Guatemalan": "Guatemala",
    "Guatemalans": "Guatemala",
    "Guernsey": "Guernsey",
    "Guernseyman and Guernseywoman": "Guernsey",
    "Guinean": "Guinea",
    "Guineans": "Guinea",
    "Bissau-Guinean": "Guinea-Bissau",
    "Bissau-Guineans": "Guinea-Bissau",
    "Guyanese": "Guyana",
    "Haitian": "Haiti",
    "Haitians": "Haiti",
    "Heard Island": "Heard Island and McDonald Islands",
    "McDonald Island": "Heard Island and McDonald Islands",
    "Heard Islanders": "Heard Island and McDonald Islands",
    "McDonald Islanders": "Heard Island and McDonald Islands",
    "Honduran": "Honduras",
    "Hondurans": "Honduras",
    "Hong Kong": "Hong Kong",
    "Cantonese": "Hong Kong",
    "Hong Konger": "Hong Kong",
    "Hongkongers": "Hong Kong",
    "Hong Kongese": "Hong Kong",
    "Hungarian": "Hungary",
    "Magyar": "Hungary",
    "Hungarians": "Hungary",
    "Magyars": "Hungary",
    "Icelandic": "Iceland",
    "Icelanders": "Iceland",
    "Indian": "India",
    "Indians": "India",
    "Indonesian": "Indonesia",
    "Indonesians": "Indonesia",
    "Iranian": "Iran",
    "Persian": "Iran",
    "Iranians": "Iran",
    "Persians": "Iran",
    "Iraqi": "Iraq",
    "Iraqis": "Iraq",
    "Irish": "Ireland",
    "Irishmen and Irishwomen": "Ireland",
    "Manx": "Isle of Man",
    "Israeli": "Israel",
    "Israelite": "Israel",
    "Israelis": "Israel",
    "Italian": "Italy",
    "Italians": "Italy",
    "Ivorian": "Ivory Coast",
    "Ivorians": "Ivory Coast",
    "Jamaican": "Jamaica",
    "Jamaicans": "Jamaica",
    "Jan Mayen": "Jan Mayen",
    "Jan Mayen residents": "Jan Mayen",
    "Japanese": "Japan",
    "Jersey": "Jersey",
    "Jerseyman and Jerseywoman": "Jersey",
    "Jersian": "Jersey",
    "Jèrriais": "Jersey",
    "Jordanian": "Jordan",
    "Jordanians": "Jordan",
    "Kazakhstani": "Kazakhstan",
    "Kazakh": "Kazakhstan",
    "Kazakhstanis": "Kazakhstan",
    "Kazakhs": "Kazakhstan",
    "Kenyan": "Kenya",
    "Kenyans": "Kenya",
    "Kiribati": "Kiribati",
    "I-Kiribati": "Kiribati",
    "North Korean": "North Korea",
    "Koreans": "South Korea",
    "North Koreans": "North Korea",
    "South Korean": "South Korea",
    "South Koreans": "South Korea",
    "Kosovar": "Kosovo",
    "Kosovan": "Kosovo",
    "Kosovars": "Kosovo",
    "Kuwaiti": "Kuwait",
    "Kuwaitis": "Kuwait",
    "Kyrgyzstani": "Kyrgyzstan",
    "Kyrgyz": "Kyrgyzstan",
    "Kirgiz": "Kyrgyzstan",
    "Kirghiz": "Kyrgyzstan",
    "Kyrgyzstanis": "Kyrgyzstan",
    "Lao": "Laos",
    "Laotian": "Laos",
    "Laos": "Laos",
    "Laotians": "Laos",
    "Latvian": "Latvia",
    "Lettish": "Latvia",
    "Latvians": "Latvia",
    "Letts": "Latvia",
    "Lebanese": "Lebanon",
    "Basotho": "Lesotho",
    "Basotho (singular Mosotho)": "Lesotho",
    "Liberian": "Liberia",
    "Liberians": "Liberia",
    "Libyan": "Libya",
    "Libyans": "Libya",
    "Liechtensteiner": "Liechtenstein",
    "Liechtensteiners": "Liechtenstein",
    "Lithuanian": "Lithuania",
    "Lithuanians": "Lithuania",
    "Luxembourg": "Luxembourg",
    "Luxembourgish": "Luxembourg",
    "Luxembourgers": "Luxembourg",
    "Macanese": "Macau",
    "Malagasy": "Madagascar",
    " Madagascan": "Madagascar",
    " Madagascans": "Madagascar",
    "Malawian": "Malawi",
    "Malawians": "Malawi",
    "Malaysian": "Malaysia",
    "Malaysians": "Malaysia",
    "Maldivian": "Maldives",
    "Maldivians": "Maldives",
    "Malian": "Mali",
    "Malinese": "Mali",
    "Malians": "Mali",
    "Maltese": "Malta",
    "Marshallese": "Marshall Islands",
    "Martiniquais": "Martinique",
    "Martinican": "Martinique",
    "Martiniquaises": "Martinique",
    "Mauritanian": "Mauritania",
    "Mauritanians": "Mauritania",
    "Mauritian": "Mauritius",
    "Mauritians": "Mauritius",
    "Mahoran": "Mayotte",
    "Mahorans": "Mayotte",
    "Mexican": "Mexico",
    "Mexicans": "Mexico",
    "Micronesian": "Micronesia",
    "Micronesians": "Micronesia",
    "Moldovan": "Moldova",
    "Moldovans": "Moldova",
    "Monegasque": "Monaco",
    "Monégasque": "Monaco",
    "Monacan": "Monaco",
    "Monégasques": "Monaco",
    "Monacans": "Monaco",
    "Mongolian": "Mongolia",
    "Mongolians": "Mongolia",
    "Mongols": "Mongolia",
    "Montenegrin": "Montenegro",
    "Montenegrins": "Montenegro",
    "Montserratian": "Montserrat",
    "Montserratians": "Montserrat",
    "Moroccan": "Morocco",
    "Moroccans": "Morocco",
    "Mozambican": "Mozambique",
    "Mozambicans": "Mozambique",
    "Myanma": "Myanmar",
    "Myanmars": "Myanmar",
    "Namibian": "Namibia",
    "Namibians": "Namibia",
    "Nauruan": "Nauru",
    "Nauruans": "Nauru",
    "Nepali": "Nepal",
    "Nepalese": "Nepal",
    "Nepalis": "Nepal",
    "Dutch": "Netherlands",
    "Dutchmen and Dutchwomen": "Netherlands",
    "Netherlanders": "Netherlands",
    "New Caledonian": "New Caledonia",
    "New Caledonians": "New Caledonia",
    "New Zealand": "New Zealand",
    "New Zealander": "New Zealand",
    "New Zealanders": "New Zealand",
    "Nicaraguan": "Nicaragua",
    "Nicaraguans": "Nicaragua",
    "Nigerien": "Niger",
    "Nigeriens": "Niger",
    "Nigerian": "Nigeria",
    "Nigerians": "Nigeria",
    "Niuean": "Niue",
    "Niueans": "Niue",
    "Norfolk Island": "Norfolk Island",
    "Norfolk Islanders": "Norfolk Island",
    "Macedonian": "North Macedonia",
    "Macedonians": "North Macedonia",
    "Northern Irish": "Northern Ireland",
    "Northern Irishmen and Northern Irishwomen": "Northern Ireland",
    "Northern Marianan": "Northern Mariana Islands",
    "Northern Marianans": "Northern Mariana Islands",
    "Norwegian": "Norway",
    "Norwegians": "Norway",
    "Omani": "Oman",
    "Omanis": "Oman",
    "Pakistani": "Pakistan",
    "Pakistanis": "Pakistan",
    "Palauan": "Palau",
    "Palauans": "Palau",
    "Palestinian": "Palestine",
    "Palestinians": "Palestine",
    "Panamanian": "Panama",
    "Panamanians": "Panama",
    "Papua New Guinean": "Papua New Guinea",
    "Papuan": "Papua New Guinea",
    "Papua New Guineans": "Papua New Guinea",
    "Papuans": "Papua New Guinea",
    "Paraguayan": "Paraguay",
    "Paraguayans": "Paraguay",
    "Peruvian": "Peru",
    "Peruvians": "Peru",
    "Filipino": "Philippines",
    "Philippine": "Philippines",
    "Filipinos": "Philippines",
    "Filipinas": "Philippines",
    "Pitcairn Island": "Pitcairn Islands",
    "Pitcairn Islanders": "Pitcairn Islands",
    "Polish": "Poland",
    "Poles": "Poland",
    "Portuguese": "Portugal",
    "Puerto Rican": "Puerto Rico",
    "Puerto Ricans": "Puerto Rico",
    "Qatari": "Qatar",
    "Qataris": "Qatar",
    "Réunionese": "Réunion",
    "Réunionnais": "Réunion",
    "Réunionnais and Réunionnaises": "Réunion",
    "Romanian": "Romania",
    "Romanians": "Romania",
    "Russian": "Russia",
    "Russians": "Russia",
    "Rwandan": "Rwanda",
    "Rwandans": "Rwanda",
    "Banyarwanda": "Rwanda",
    "Saba": "Saba",
    "Saban": "Saba",
    "Saba Dutch": "Saba",
    "Barthélemois": "Saint Barthélemy",
    "Barthélemoises": "Saint Barthélemy",
    "Saint Helenian": "'Saint Helena",
    "Saint Helenians": "'Saint Helena",
    "Kittitian": "Saint Kitts and Nevis",
    "Nevisian": "Saint Kitts and Nevis",
    "Kittitians": "Saint Kitts and Nevis",
    "Nevisians": "Saint Kitts and Nevis",
    "Saint Lucian": "Saint Lucia",
    "Saint Lucians": "Saint Lucia",
    "Saint-Martinoise": "Saint Martin",
    "Saint-Martinois": "Saint Martin",
    "Saint-Martinoises": "Saint Martin",
    "Saint-Pierrais": "Saint Pierre and Miquelon",
    "Miquelonnais": "Saint Pierre and Miquelon",
    "Saint-Pierraises": "Saint Pierre and Miquelon",
    "Miquelonnaises": "Saint Pierre and Miquelon",
    "Saint Vincentian": "Saint Vincent and the Grenadines",
    "Vincentian": "Saint Vincent and the Grenadines",
    "Saint Vincentians": "Saint Vincent and the Grenadines",
    "Vincentians": "Saint Vincent and the Grenadines",
    "Sahrawi": "Western Sahara",
    "Western Saharan": "Sahrawi",
    "Sahrawian": "Western Sahara",
    "Sahrawis": "Western Sahara",
    "Western Saharans": "Sahrawi",
    "Samoan": "Samoa",
    "Samoans": "Samoa",
    "Sammarinese": "San Marino",
    "São Toméan": "São Tomé and Príncipe",
    "São Toméans": "São Tomé and Príncipe",
    "Saudi": "Saudi Arabia",
    "Saudi Arabian": "Saudi Arabia",
    "Saudis": "Saudi Arabia",
    "Saudi Arabians": "Saudi Arabia",
    "Scottish": "Scotland",
    "Scots": "Scotland",
    "Scotsmen and Scotswomen": "Scotland",
    "Senegalese": "Senegal",
    "Serbian": "Serbia",
    "Serbs": "Serbia",
    "Serbians": "Serbia",
    "Seychellois": "Seychelles",
    "Seychellois/Seychelloises": "Seychelles",
    "Sierra Leonean": "Sierra Leone",
    "Sierra Leoneans": "Sierra Leone",
    "Singapore": "Singapore",
    "Singaporean": "Singapore",
    "Singaporeans": "Singapore",
    "Sint Eustatius": "Sint Eustatius",
    "Statian": "Sint Eustatius",
    "Statians": "Sint Eustatius",
    "Sint Maarten": "Sint Maarten",
    "Sint Maarteners": "Sint Maarten",
    "Slovak": "Slovakia",
    "Slovaks": "Slovakia",
    "Slovakians": "Slovakia",
    "Slovenian": "Slovenia",
    "Slovene": "Slovenia",
    "Slovenes": "Slovenia",
    "Slovenians": "Slovenia",
    "Solomon Island": "Solomon Islands",
    "Solomon Islanders": "Solomon Islands",
    "Somali": "Somalia",
    "Somalian": "Somalia",
    "Somalians": "Somalia",
    "Somalilander": "Somaliland",
    "Somalilanders": "Somaliland",
    "South African": "South Africa",
    "South Africans": "South Africa",
    "South Georgia Island": "South Georgia and the South Sandwich Islands",
    "South Sandwich Island": "South Georgia and the South Sandwich Islands",
    "South Georgia Islanders": "South Georgia and the South Sandwich Islands",
    "South Sandwich Islanders": "South Georgia and the South Sandwich Islands",
    "South Ossetian": "South Ossetia",
    "South Ossetians": "South Ossetia",
    "South Sudanese": "South Sudan",
    "Spanish": "Spain",
    "Spaniards": "Spain",
    "Sri Lankan": "Sri Lanka",
    "Sri Lankans": "Sri Lanka",
    "Sudanese": "Sudan",
    "Surinamese": "Suriname",
    "Surinamers": "Suriname",
    "Svalbard": "Svalbard",
    "Svalbard residents": "Svalbard",
    "Swedish": "Sweden",
    "Swedes": "Sweden",
    "Swiss": "Switzerland",
    "Syrian": "Syria",
    "Syrians": "Syria",
    "Taiwanese": "Taiwan",
    "Formosan": "Taiwan",
    "Formosans": "Taiwan",
    "Tajikistani": "Tajikistan",
    "Tajikistanis": "Tajikistan",
    "Tajiks": "Tajikistan",
    "Tanzanian": "Tanzania",
    "Tanzanians": "Tanzania",
    "Thai": "Thailand",
    "Togolese": "Togo",
    "Tokelauan": "Tokelau",
    "Tokelauans": "Tokelau",
    "Tongan": "Tonga",
    "Tongans": "Tonga",
    "Trinidadian": "Trinidad and Tobago",
    "Tobagonian": "Trinidad and Tobago",
    "Trinidadians": "Trinidad and Tobago",
    "Tobagonians": "Trinidad and Tobago",
    "Tunisian": "Tunisia",
    "Tunisians": "Tunisia",
    "Turkish": "Turkey",
    "Turks": "Turkey",
    "Turkmen": "Turkmenistan",
    "Turkmens": "Turkmenistan",
    "Turks and Caicos Island": "Turks and Caicos Islands",
    "Turks and Caicos Islanders": "Turks and Caicos Islands",
    "Tuvaluan": "Tuvalu",
    "Tuvaluans": "Tuvalu",
    "Ugandan": "Uganda",
    "Ugandans": "Uganda",
    "Ukrainian": "Ukraine",
    "Ukrainians": "Ukraine",
    "Emirati": "United Arab Emirates",
    "Emirian": "United Arab Emirates",
    "Emiri": "United Arab Emirates",
    "Emiratis": "United Arab Emirates",
    "Emirians": "United Arab Emirates",
    "United Kingdom": "United Kingdom of Great Britain and Northern Ireland",
    "UK": "United Kingdom of Great Britain and Northern Ireland",
    "Britons": "United Kingdom of Great Britain and Northern Ireland",
    "British people": "United Kingdom of Great Britain and Northern Ireland",
    "American": "United States of America",
    "United States": "United States of America",
    "U.S.": "United States of America",
    "Americans": "United States of America",
    " New Englanders": "United States of America",
    "Uruguayan": "Uruguay",
    "Uruguayans": "Uruguay",
    "Uzbekistani": "Uzbekistan",
    "Uzbek": "Uzbekistan",
    "Uzbekistanis": "Uzbekistan",
    "Uzbeks": "Uzbekistan",
    "Ni-Vanuatu": "Vanuatu",
    "Vanuatuan": "Vanuatu",
    "Vaticanian": "Vatican City",
    "Vaticanians": "Vatican City",
    "Venezuelan": "Venezuela",
    "Venezuelans": "Venezuela",
    "Vietnamese": "Vietnam",
    "British Virgin Island": "British Virgin Islands",
    "British Virgin Islanders": "British Virgin Islands",
    "U.S. Virgin Island": "United States Virgin Islands",
    "U.S. Virgin Islanders": "United States Virgin Islands",
    "Welsh": "Wales",
    "Welshmen": "Wales",
    "Welshwomen": "Wales",
    "Wallis and Futuna": "Wallis and Futuna",
    "Wallisian": "Wallis and Futuna",
    "Futunan": "Wallis and Futuna",
    "Wallis and Futuna Islanders": "Wallis and Futuna",
    "Wallisians": "Wallis and Futuna",
    "Futunans": "Wallis and Futuna",
    "Sahraouian": "Western Sahara",
    "Sahraouis": "Western Sahara",
    "Yemeni": "Yemen",
    "Yemenis": "Yemen",
    "Zambian": "Zambia",
    "Zambians": "Zambia",
    "Zanzibari": "Zanzibar",
    "Zanzibaris": "Zanzibar",
    "Zimbabwean": "Zimbabwe",
    "Zimbabweans": "Zimbabwe"
};